groups:
  - name: Linux_CPU_Alerts
    rules:
      - alert: HostHighCpuLoad_warning
        expr: (sum by (instance) (avg by (mode, instance) (rate(node_cpu_seconds_total{mode!="idle"}[2m]))) > 0.8) * on(instance) group_left (nodename) node_uname_info{nodename=~".+"}
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Host high CPU load (instance {{ $labels.instance }})
          description: "CPU load is > 80%\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"          
      - alert: HostHighCpuLoad_critical
        expr: (sum by (instance) (avg by (mode, instance) (rate(node_cpu_seconds_total{mode!="idle"}[2m]))) > 0.98) * on(instance) group_left (nodename) node_uname_info{nodename=~".+"}
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: Host high CPU load (instance {{ $labels.instance }})
          description: "CPU load is > 98%\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"          
      - alert: HostCpuHighIowait_warning
        expr: (avg by (instance) (rate(node_cpu_seconds_total{mode="iowait"}[5m])) * 100 > 50) * on(instance) group_left (nodename) node_uname_info{nodename=~".+"}
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: Host CPU high iowait (instance {{ $labels.instance }})
          description: "CPU iowait > 50%. A high iowait means that you are disk or network bound.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"                    
      - alert: HostCpuHighIowait_critical
        expr: (avg by (instance) (rate(node_cpu_seconds_total{mode="iowait"}[5m])) * 100 > 90) * on(instance) group_left (nodename) node_uname_info{nodename=~".+"}
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: Host CPU high iowait (instance {{ $labels.instance }})
          description: "CPU iowait > 20%. A high iowait means that you are disk or network bound.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"                    
  - name: Linux_Memory_Alerts
    rules:
      - alert: HostOutOfMemory_warning
        expr: |
          (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 < 10) * on(instance) 
          group_left (nodename) node_uname_info{nodename=~".+"}
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: Host out of memory (instance {{ $labels.instance }})
          description: |
            "Node memory is filling up (< 10% left)
            VALUE = {{ $value }}
            LABELS = {{ $labels }}"
      - alert: HostOutOfMemory_critical
        expr: |
          (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 < 3) * on(instance) 
          group_left (nodename) node_uname_info{nodename=~".+"}
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: Host out of memory (instance {{ $labels.instance }})
          description: |
            "Node memory is filling up (< 3% left)
            VALUE = {{ $value }}
            LABELS = {{ $labels }}"
      - alert: HostMemoryUnderMemoryPressure
        expr: |
          (rate(node_vmstat_pgmajfault[1m]) > 1000) * on(instance) 
          group_left (nodename) node_uname_info{nodename=~".+"}
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: Host memory under memory pressure (instance {{ $labels.instance }})
          description: "The node is under heavy memory pressure. High rate of major page faults\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"          
  - name: Linux_Disk_Alerts
    rules:
      - alert: HostOutOfDiskSpace_warning
        expr: ((node_filesystem_avail_bytes * 100) / node_filesystem_size_bytes < 10 and ON (instance, device, mountpoint) node_filesystem_readonly == 0) * on(instance) group_left (nodename) node_uname_info{nodename=~".+"}
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Host out of disk space (instance {{ $labels.instance }})
          description: "Disk is almost full (< 10% left)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
      - alert: HostOutOfDiskSpace_critical
        expr: ((node_filesystem_avail_bytes * 100) / node_filesystem_size_bytes < 2 and ON (instance, device, mountpoint) node_filesystem_readonly == 0) * on(instance) group_left (nodename) node_uname_info{nodename=~".+"}
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: Host out of disk space (instance {{ $labels.instance }})
          description: "Disk is almost full (< 2% left)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"          
      - alert: HostDiskWillFillIn24Hours
        expr: ((node_filesystem_avail_bytes * 100) / node_filesystem_size_bytes < 10 and ON (instance, device, mountpoint) predict_linear(node_filesystem_avail_bytes{fstype!~"tmpfs"}[1h], 24 * 3600) < 0 and ON (instance, device, mountpoint) node_filesystem_readonly == 0) * on(instance) group_left (nodename) node_uname_info{nodename=~".+"}
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: Host disk will fill in 24 hours (instance {{ $labels.instance }})
          description: "Filesystem is predicted to run out of space within the next 24 hours at current write rate\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
      - alert: HostOutOfInodes
        expr: (node_filesystem_files_free{fstype!="msdosfs"} / node_filesystem_files{fstype!="msdosfs"} * 100 < 10 and ON (instance, device, mountpoint) node_filesystem_readonly == 0) * on(instance) group_left (nodename) node_uname_info{nodename=~".+"}
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: Host out of inodes (instance {{ $labels.instance }})
          description: "Disk is almost running out of available inodes (< 10% left)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"          
  - name: Linux_Load_Alerts
    rules:
    - alert: high_load_warning
      expr: sum by(instance) (node_load1) / count by(instance) (node_cpu_seconds_total{mode="idle"}) > 0.8
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "Instance {{ $labels.instance }} under high load"
        description: "{{ $labels.instance }} of job {{ $labels.job }} is under high load. VALUE = {{ $value }}"
    - alert: high_load_critical
      expr: sum by(instance) (node_load1) / count by(instance) (node_cpu_seconds_total{mode="idle"}) > 1
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Instance {{ $labels.instance }} under high load"
        description: "{{ $labels.instance }} of job {{ $labels.job }} is under high load. VALUE = {{ $value }}"